import { ref, computed, watch, onMounted } from "vue";

export type AppLang = "ar" | "en";

const currentLang = ref<AppLang>("ar");

export const translations = {
  ar: {
    dir: "rtl",
    brand: "بروج",
    brandSubtitle: "المميزة للسياحة",
    licenseShort: "ترخيص سياحي:",
    nav: {
      home: "الرئيسية",
      about: "من نحن",
      services: "خدماتنا",
      prices: "قائمة الأسعار",
      hotels: "فنادق شركاؤنا",
      policies: "السياسات والضمانات",
      contact: "الشكاوى والاستفسارات",
      directBooking: "حجز ودفع مباشر",
      dashboard: "لوحة التحكم",
      viewSite: "عرض الموقع",
      login: "دخول الإدارة",
      logout: "خروج",
      toggleTheme: "تبديل المظهر",
      langSwitch: "English",
    },
    legal: {
      tradeName: "مؤسسة بروج المميزة للسياحة",
      crLabel: "سجل تجاري:",
      licenseLabel: "ترخيص وزارة السياحة:",
      categoryLabel: "فئة الترخيص:",
      support247: "خدمة 24/7 متواصلة",
      inquiriesComplaints247: "استفسارات وشكاوى 24/7",
      acceptedCards: "طرق الدفع الإلكتروني المعتمدة:",
      rightsReserved: "جميع الحقوق محفوظة لمؤسسة بروج المميزة للسياحة",
      locationCity: "مكة المكرمة - المملكة العربية السعودية",
    },
    supportBadge: {
      title: "خدمة العملاء والشكاوى (24/7)",
      desc: "فريقنا متاح على مدار الساعة لاستقبال استفسارات الحجز، طلبات التعديل، والشكاوى والمقترحات.",
      chatWhatsapp: "محادثة واتساب مباشرة (24/7)",
      callDirect: "الاتصال الهاتفي المباشر",
      submitTicket: "تقديم شكوى أو استفسار رسمي",
      slaNotice: "البت في الشكاوى: خلال 24 ساعة",
      shortLabel: "24/7",
    },
    hero: {
      bookNow: "احجز إقامتك الآن",
      exploreServices: "استكشف الخدمات",
    },
    about: {
      badge: "عن المنشأة",
      title: "من نحن",
      yearsExp: "سنوات من الخبرة",
      partnerHotels: "فندق شريك مرخص",
      happyGuests: "عميل سعيد ومقيم",
      supportService: "خدمة واستفسارات وشكاوى",
    },
    services: {
      badge: "ماذا نقدم لعملائنا",
      title: "خدماتنا المتميزة",
      ctaTitle: "جاهز لحجز رحلتك القادمة؟",
      ctaSubtitle: "تواصل مع خبرائنا لاختيار الفندق الأنسب لك ولعائلتك بأفضل الأسعار",
      ctaBtn: "تواصل للحجز الآن",
    },
    prices: {
      badge: "أسعار شاملة الضريبة والرسوم",
      title: "قائمة أسعار الخدمات الفندقية والسياحية",
      subtitle: "جميع الأسعار المعروضة نهائية ومشتملة على ضريبة القيمة المضافة (15%) وكافة الرسوم النظامية",
      statementTitle: "إقرار الشفافية وضمان شمول الضرائب والرسوم (المادة العشرون من لائحة خدمات السفر والسياحة):",
      statementBody: "تلتزم مؤسسة بروج المميزة للسياحة بإعلان أسعار كافة الخدمات الفندقية والسياحية شاملة ضريبة القيمة المضافة (15%) وكافة الرسوم النظامية ضمن السعر الإجمالي المعروض.",
      currencySar: "ريال سعودي",
      vatIncluded: "السعر شامل ضريبة القيمة المضافة 15% وكافة الرسوم",
      permitLabel: "تصريح رقم:",
      bookAndPay: "احجز وادفع الآن",
    },
    hotels: {
      badge: "مرافق مرخصة ومصنفة",
      title: "فنادق وشركاء الإقامة المرخصة",
      subtitle: "جميع المرافق والوحدات المعروضة حاصلة على تراخيص وتصاريح نظامية من وزارة السياحة",
      permitLabel: "رقم التصريح:",
      startsFrom: "يبدأ من",
      perNight: "ر.س / ليلة",
      vatIncluded: "شامل الضريبة (15%)",
      vatIncludedShort: "أسعار شاملة الضريبة",
      directBookingBtn: "حجز مباشر",
      emptyStateTitle: "جاري تدقيق وتحديث تصاريح المرافق الفندقية",
      emptyStateDesc: "وفقاً لضوابط وزارة السياحة، لا يتم عرض أي مرفق أو وحدة إلا بعد اكتمال التحقق من رقم الترخيص الصادر.",
      viewOnMap: "عرض الموقع على الخريطة",
    },
    contact: {
      badge: "استفسارات وشكاوى (24/7)",
      title: "خدمة العملاء والشكاوى والاستفسارات",
      formHeader: "تقديم استفسار أو شكوى رسمية",
      availableNow: "الرد على مدار الساعة",
      typeLabel: "نوع الطلب أو الرسالة",
      typeHelp: "نلتزم بالرد على الاستفسارات والبت في الشكاوى خلال 24 ساعة كحد أقصى",
      types: {
        inquiry: "استفسار عام عن الخدمات أو الأسعار",
        complaint: "شكوى أو بلاغ عن خدمة",
        booking: "طلب حجز مخصص أو مجموعة",
        cancelOrMod: "طلب تعديل أو إلغاء حجز",
      },
      nameLabel: "الاسم الكامل",
      namePlaceholder: "أدخل اسمك الكريم",
      emailLabel: "البريد الإلكتروني",
      phoneLabel: "رقم الجوال / الواتساب",
      subjectLabel: "موضوع الطلب",
      subjectPlaceholder: "مثال: استفسار عن حجز / طلب تعديل / شكوى خدمة",
      messageLabel: "نص الرسالة أو تفاصيل الشكوى / الحجز",
      messagePlaceholder: "اكتب تفاصيل طلبك، رقم الحجز إن وجد، أو تفاصيل الشكوى بدقة لمساعدتنا على خدمتك سريعاً...",
      checkInLabel: "تاريخ تسجيل الدخول (Check-in)",
      checkOutLabel: "تاريخ تسجيل الخروج (Check-out)",
      guestsLabel: "عدد النزلاء / الضيوف",
      roomsLabel: "عدد الغرف / الوحدات",
      notesLabel: "ملاحظات أو طلبات خاصة (اختياري)",
      notesPlaceholder: "أي طلبات خاصة مثل إطلالة معينة، سرير إضافي، وصول متأخر، إلخ...",
      statutoryCommitment: "وفقاً للائحة خدمات السفر والسياحة الصادرة عن وزارة السياحة، تلتزم مؤسسة بروج المميزة بالرد الفوري على الاستفسارات ومتابعة الشكاوى وحلها على مدار 24 ساعة.",
      submitBtn: "إرسال الطلب / الشكوى الآن",
      channelsTitle: "قنوات التواصل المباشر (24/7)",
      phoneCall: "الاتصال الهاتفي المباشر",
      whatsappChat: "واتساب الاستفسارات والشكاوى (24/7)",
      officialEmail: "البريد الإلكتروني الرسمي",
      workAndLicenseTitle: "أوقات العمل والدعم والترخيص",
      directBookingPromptTitle: "ترغب في الحجز والسداد المباشر؟",
      directBookingPromptDesc: "يمكنك استعراض أسعار الغرف الشاملة للضريبة، واختيار تواريخ إقامتك، والدفع مباشرة ببطاقات فيزا أو ماستركارد مع إصدار فوري لمستند الحجز.",
      directBookingPromptBtn: "الانتقال لصفحة الحجز والدفع الإلكتروني",
    },
    policies: {
      pageTitle: "السياسات والشروط والضمانات النظامية",
      pageDesc: "معدّة وفقاً للائحة خدمات السفر والسياحة الصادرة عن وزارة السياحة بالمملكة العربية السعودية (المواد 18، 20، 22، 23).",
      p1Title: "1. سياسة وشروط الحجز وإصدار المستند (المادة الثانية والعشرون — الفقرة ١ و ١/أ)",
      p1Subtitle: "إبلاغ طالب الخدمة بكافة الشروط وإصدار مستند حجز فوري معتمد.",
      p2Title: "2. سياسة طلب إلغاء أو تعديل الحجز والمدة المحددة للرد (المادة الثانية والعشرون — الفقرة ١/أ)",
      p2Subtitle: "آلية تقديم الطلب والمدة الزمنية المحددة للبت فيه من قبل المنشأة.",
      p2Sla: "المدة المحددة للرد: خلال 24 ساعة كحد أقصى",
      p3Title: "3. سياسة مبالغ التأمين وشروط استرجاعها (المادة الثانية والعشرون — الفقرة ٢/أ)",
      p3Subtitle: "توضيح مبالغ التأمين المطلوبة -إن وجدت- وآلية دفعها واسترجاعها.",
      p4Title: "4. سياسة الاسترجاع عند تعذر تقديم الخدمة المتفق عليها (المادة الثالثة والعشرون)",
      p4Subtitle: "تخيير السائح بين خدمة بديلة مساوية أو استرجاع كامل المبالغ فوراً دون خصم أي رسوم.",
      p4Sla: "تنفيذ الاسترجاع: خلال 1-3 أيام عمل",
      ctaTitle: "جاهز لبدء حجزك الفندقي المباشر؟",
      ctaDesc: "سداد إلكتروني مباشر ببطاقات فيزا وماستركارد وإصدار فوري لمستند الحجز.",
      ctaBtn: "الحجز والدفع المباشر",
      contactChannels: "قنوات الاستفسار (24/7)",
    },
    booking: {
      pageTitle: "خدمة الحجز والدفع الإلكتروني المباشر",
      pageDesc: "احجز إقامتك الفندقية وادفع فوراً عبر بطاقات الائتمان (فيزا وماستركارد) بأسعار معلنة وشاملة لضريبة القيمة المضافة (15%) وكافة الرسوم النظامية.",
      sandboxNoticeTitle: "بوابة السداد في وضع الاختبار والتجربة (Moyasar Sandbox):",
      sandboxNoticeBody: "يمكنك اختبار إجراء عملية حجز وسداد تجريبية ناجحة ببطاقات فيزا وماستركارد الاختبارية، مع إصدار فوري لمستند الحجز المعتمد.",
      step1: "1. اختيار الخدمة أو الوحدة الفندقية المرخصة",
      step2: "2. تواريخ الإقامة وعدد الضيوف",
      step3: "3. بيانات الضيف الأساسية للتأكيد وإصدار السند",
      step4: "4. الإقرار بالموافقة على الشروط والسياسات النظامية",
      checkIn: "تاريخ تسجيل الدخول (Check-in)",
      checkOut: "تاريخ تسجيل الخروج (Check-out)",
      guests: "عدد النزلاء / الضيوف",
      rooms: "عدد الغرف / الوحدات",
      guestFullName: "الاسم الثلاثي (كما بالهوية / الجواز)",
      guestPhone: "رقم الجوال للتواصل وتأكيد الحجز",
      guestEmail: "البريد الإلكتروني لإرسال مستند الحجز الرسمي",
      guestNotes: "ملاحظات أو طلبات خاصة (اختياري)",
      agreePolicies: "أوافق على شروط وسياسة الحجز وسياسة الإلغاء والتعديل (تلتزم المنشأة بالبت والرد على طلب الإلغاء/التعديل خلال مدة أقصاها 24 ساعة).",
      agreeRefund: "أقر باطلاعي على ضمان حقوق السائح واسترجاع المبالغ وفق المادة (23) (تخيير العميل بين خدمة بديلة مساوية أو استرجاع فوري كامل دون خصم أي رسوم في حال تعذر تقديم الخدمة).",
      agreeInsurance: "أعلم بأنه لا يُطلب أي مبلغ تأمين إضافي عبر الموقع الإلكتروني.",
      summaryTitle: "ملخص الفاتورة والسداد",
      summaryVatInclusive: "سعر إجمالي شامل الضريبة",
      nightsCalculated: "عدد الليالي المحسوبة:",
      subtotalBeforeVat: "المبلغ الأساسي قبل الضريبة:",
      vatAmount: "ضريبة القيمة المضافة النظامية (15%):",
      insuranceAmount: "مبلغ التأمين المطلوب:",
      noInsurance: "0.00 ر.س (لا يُطلب تأمين)",
      grandTotal: "الإجمالي النهائي المطلوب:",
      vatIncludedFooter: "شامل 15% ضريبة وكافة الرسوم",
      directCardsTitle: "الدفع المباشر عبر بطاقات الائتمان المعتمدة:",
      gatewaySecurity: "معالجة آمنة ومشفرة مباشرة بالتعاون مع بوابة ميسار (Moyasar) المرخصة من البنك المركزي السعودي.",
      payBtn: "الانتقال للسداد بـ فيزا / ماستركارد",
      incompletePrompt: "* يرجى إكمال بيانات الضيف وتحديد التواريخ والموافقة على السياسات النظامية للمتابعة.",
      supportQuestion: "هل تواجه أي استفسار حول الحجز أو السداد؟",
      whatsapp247: "واتساب 24/7",
    },
    receipt: {
      verifyingTitle: "جاري التحقق من عملية السداد...",
      verifyingSubtitle: "يتم تأكيد العملية مع بوابة ميسار وتحديث سجل الحجز الرسمي.",
      successTitle: "تم تأكيد الحجز وسداد الفاتورة بنجاح!",
      successSubtitle: "تم إصدار مستند الحجز الإلكتروني المعتمد وفق اشتراطات وزارة السياحة.",
      printBtn: "طباعة مستند الحجز",
      bookingRef: "رقم مستند الحجز المرجعي:",
      guestInfo: "بيانات الضيف والحجز",
      guestName: "اسم الضيف:",
      guestPhone: "رقم الجوال:",
      guestEmail: "البريد الإلكتروني:",
      guestCount: "عدد النزلاء:",
      unitInfo: "بيانات الوحدة الفندقية والتواريخ",
      unitName: "الوحدة / الخدمة:",
      permitNo: "رقم ترخيص الوحدة / المرفق:",
      checkIn: "تاريخ الدخول:",
      checkOut: "تاريخ الخروج:",
      stayDuration: "مدة الإقامة:",
      feeBreakdown: "تفاصيل الرسوم والضرائب المسددة",
      baseAmount: "المبلغ الأساسي للخدمة:",
      vatAmount: "ضريبة القيمة المضافة (15%) النظامية:",
      depositAmount: "مبلغ التأمين المطلوب:",
      totalPaid: "المبلغ الإجمالي المسدد (شامل الضريبة والرسوم):",
      payMethod: "طريقة السداد: بطاقة ائتمانية",
      payStatus: "حالة الدفع: مدفوع ومؤكد (PAID)",
      termsTitle: "الشروط والسياسات المطبقة على هذا الحجز:",
      term1: "سياسة الإلغاء والتعديل: يمكن تقديم طلب الإلغاء أو التعديل عبر الموقع أو الواتساب، وتلتزم المنشأة بالرد والبت في الطلب خلال 24 ساعة كحد أقصى.",
      term2: "سياسة الاسترجاع (المادة 23): عند تعذر تقديم الخدمة المحجوزة لأي سبب خارج عن إرادة العميل، يتم تخيير السائح بين توفير خدمة بديلة مساوية أو استرجاع كامل المبالغ فوراً دون خصم أي رسوم.",
      term3: "الدعم المتواصل (24/7): مركز خدمة العملاء والشكاوى متاح على مدار الساعة.",
      returnHome: "العودة للرئيسية",
      viewPolicies: "استعراض كافة اللوائح والسياسات",
      failedTitle: "لم تكتمل عملية السداد",
      failedDesc: "تم إلغاء عملية الدفع أو تعذر سحب المبلغ من بطاقتك الائتمانية.",
      retryBtn: "إعادة المحاولة والدفع",
      instantSupport: "مساعدة فورية عبر واتساب (24/7)",
    },
    footer: {
      quickLinks: "أقسام الموقع",
      statutoryPolicies: "السياسات والضمانات النظامية",
      complaintsSupport: "الاستفسارات والشكاوى (24/7)",
      complaintsDesc: "تلتزم المنشأة بالرد على كافة الاستفسارات والشكاوى على مدار الساعة طوال أيام الأسبوع:",
      bookingPolicy: "سياسة وشروط الحجز والدفع",
      cancelPolicy: "سياسة الإلغاء والتعديل (رد خلال 24 ساعة)",
      depositPolicy: "سياسة مبالغ التأمين",
      refundPolicy: "سياسة الاسترجاع (المادة 23 - بديل أو رد فوري)",
      adminPortal: "بوابة الإدارة",
      stayFollow: "تابعنا وتواصل",
      stayFollowDesc: "تابع أحدث عروض الفنادق والإقامات الموسمية عبر قنوات التواصل الخاصة بنا:",
    },
  },
  en: {
    dir: "ltr",
    brand: "Burouj",
    brandSubtitle: "Tourism Services",
    licenseShort: "Tourism License:",
    nav: {
      home: "Home",
      about: "About Us",
      services: "Services",
      prices: "Price List",
      hotels: "Partner Hotels",
      policies: "Policies & Terms",
      contact: "Inquiries & Complaints",
      directBooking: "Book & Pay Online",
      dashboard: "Dashboard",
      viewSite: "View Website",
      login: "Admin Login",
      logout: "Logout",
      toggleTheme: "Toggle Theme",
      langSwitch: "العربية",
    },
    legal: {
      tradeName: "Burouj Al Mumayaza Tourism Est.",
      crLabel: "CR Number:",
      licenseLabel: "Ministry of Tourism License:",
      categoryLabel: "License Category:",
      support247: "24/7 Continuous Support",
      inquiriesComplaints247: "24/7 Inquiries & Complaints",
      acceptedCards: "Approved Electronic Payment Methods:",
      rightsReserved: "All rights reserved to Burouj Al Mumayaza Tourism Est.",
      locationCity: "Makkah Al Mukarramah - Kingdom of Saudi Arabia",
    },
    supportBadge: {
      title: "Customer Support & Complaints (24/7)",
      desc: "Our team is available round the clock for reservations, modifications, inquiries and formal complaints.",
      chatWhatsapp: "Live WhatsApp Chat (24/7)",
      callDirect: "Direct Phone Call",
      submitTicket: "Submit Official Complaint / Inquiry",
      slaNotice: "Complaints Decision: Within 24 hours",
      shortLabel: "24/7",
    },
    hero: {
      bookNow: "Book Your Stay Now",
      exploreServices: "Explore Services",
    },
    about: {
      badge: "About Establishment",
      title: "About Us",
      yearsExp: "Years of Experience",
      partnerHotels: "Licensed Partner Hotels",
      happyGuests: "Happy Guests Served",
      supportService: "24/7 Support & Complaints",
    },
    services: {
      badge: "What We Offer",
      title: "Our Premium Services",
      ctaTitle: "Ready to Book Your Next Journey?",
      ctaSubtitle: "Contact our travel experts to select the ideal hotel for you and your family at the best rates.",
      ctaBtn: "Book Now",
    },
    prices: {
      badge: "All-Inclusive Statutory Pricing",
      title: "Services & Accommodation Price List",
      subtitle: "All prices shown are total and include 15% VAT and all statutory fees",
      statementTitle: "Statutory VAT Transparency Statement (Article 20 - Travel & Tourism Regulations):",
      statementBody: "Burouj Al Mumayaza Tourism Est. is committed to publishing all hotel and tourism service rates fully inclusive of 15% Value Added Tax (VAT) and all statutory municipal fees within the advertised total price, with instant direct online payment via Visa and Mastercard.",
      currencySar: "SAR",
      vatIncluded: "Price includes 15% VAT & all statutory fees",
      permitLabel: "Permit #:",
      bookAndPay: "Book & Pay Now",
    },
    hotels: {
      badge: "Licensed & Classified Facilities",
      title: "Licensed Partner Accommodations",
      subtitle: "All listed facilities and units carry official licenses and permits issued by the Ministry of Tourism",
      permitLabel: "Permit Number:",
      startsFrom: "Starts from",
      perNight: "SAR / Night",
      vatIncluded: "15% VAT Included",
      vatIncludedShort: "VAT Inclusive Rates",
      directBookingBtn: "Direct Booking",
      emptyStateTitle: "Hotel Permits Verification in Progress",
      emptyStateDesc: "Under Ministry of Tourism guidelines, no accommodation unit is displayed without a validated Ministry permit number.",
      viewOnMap: "View location on map",
    },
    contact: {
      badge: "Inquiries & Complaints (24/7)",
      title: "Customer Care, Inquiries & Complaints",
      formHeader: "Submit Official Inquiry or Complaint",
      availableNow: "Round-the-clock Service",
      typeLabel: "Request Category",
      typeHelp: "We commit to resolving inquiries and deciding on complaints within a maximum of 24 hours",
      types: {
        inquiry: "General inquiry on services or rates",
        complaint: "Formal complaint or service report",
        booking: "Custom group reservation request",
        cancelOrMod: "Cancellation or modification request",
      },
      nameLabel: "Full Name",
      namePlaceholder: "Enter your full name",
      emailLabel: "Email Address",
      phoneLabel: "Mobile / WhatsApp Number",
      subjectLabel: "Subject",
      subjectPlaceholder: "e.g. Booking inquiry / modification request / service complaint",
      messageLabel: "Message or Complaint Details",
      messagePlaceholder: "Please describe your request, booking ID if applicable, or complaint details to assist you swiftly...",
      checkInLabel: "Check-in Date",
      checkOutLabel: "Check-out Date",
      guestsLabel: "Number of Guests",
      roomsLabel: "Number of Rooms",
      notesLabel: "Additional Notes or Special Requests (Optional)",
      notesPlaceholder: "Any special requests like preferred view, extra bed, late arrival...",
      statutoryCommitment: "In accordance with the Ministry of Tourism Travel and Tourism Regulations, Burouj Al Mumayaza commits to prompt round-the-clock responses to inquiries and resolution of complaints (24/7).",
      submitBtn: "Submit Request / Complaint Now",
      channelsTitle: "Direct Communication Channels (24/7)",
      phoneCall: "Direct Phone Call",
      whatsappChat: "WhatsApp Support & Complaints (24/7)",
      officialEmail: "Official Email Address",
      workAndLicenseTitle: "Working Hours, Support & Licensing",
      directBookingPromptTitle: "Prefer Direct Booking & Online Payment?",
      directBookingPromptDesc: "Browse VAT-inclusive rates, select your stay dates, and pay instantly using Visa or Mastercard with instant booking document generation.",
      directBookingPromptBtn: "Go to Online Booking & Payment Page",
    },
    policies: {
      pageTitle: "Statutory Policies, Terms & Guest Rights",
      pageDesc: "Prepared in full compliance with the Ministry of Tourism Travel and Tourism Services Regulations (Articles 18, 20, 22, and 23).",
      p1Title: "1. Booking Terms & Confirmation Document (Article 22 - Paragraph 1 & 1/A)",
      p1Subtitle: "Informing guests of all terms and issuing instant verified booking confirmation documents.",
      p2Title: "2. Cancellation & Modification Policy & SLA (Article 22 - Paragraph 1/A)",
      p2Subtitle: "Mechanism for request submission and maximum resolution SLA by the establishment.",
      p2Sla: "Decision SLA: Within 24 Hours",
      p3Title: "3. Security Deposit & Insurance Policy (Article 22 - Paragraph 2/A)",
      p3Subtitle: "Clear disclosure of deposit requirements and immediate refund terms.",
      p4Title: "4. Refund Policy upon Inability to Provide Service (Article 23)",
      p4Subtitle: "Guest right to choose between an equivalent alternative service or full immediate refund without any deductions.",
      p4Sla: "Refund Execution: Within 1-3 business days",
      ctaTitle: "Ready to Book Your Direct Accommodation?",
      ctaDesc: "Direct online payment with Visa and Mastercard and instant booking document issuance.",
      ctaBtn: "Book & Pay Online",
      contactChannels: "Inquiries Channels (24/7)",
    },
    booking: {
      pageTitle: "Direct Online Booking & Payment",
      pageDesc: "Book your hotel accommodation and pay instantly via credit card (Visa & Mastercard) with advertised prices inclusive of 15% VAT and statutory fees.",
      sandboxNoticeTitle: "Payment Gateway in Testing Mode (Moyasar Sandbox):",
      sandboxNoticeBody: "You can test seamless booking and payment execution with Visa and Mastercard test cards with instant digital receipt generation.",
      step1: "1. Select Licensed Service or Accommodation Unit",
      step2: "2. Stay Dates & Number of Guests",
      step3: "3. Guest Details for Official Confirmation",
      step4: "4. Statutory Policy Acknowledgements",
      checkIn: "Check-in Date",
      checkOut: "Check-out Date",
      guests: "Number of Guests",
      rooms: "Number of Rooms / Units",
      guestFullName: "Full Name (as on ID / Passport)",
      guestPhone: "Mobile Number for Confirmation",
      guestEmail: "Email Address for Digital Confirmation",
      guestNotes: "Special Requests or Notes (Optional)",
      agreePolicies: "I agree to the Booking Terms and the Cancellation & Modification Policy (the establishment commits to deciding on requests within max 24 hours).",
      agreeRefund: "I acknowledge tourist rights and refund guarantees under Article 23 (choice of equivalent alternative or full immediate refund without deductions).",
      agreeInsurance: "I acknowledge that no extra security deposit is charged through the website.",
      summaryTitle: "Invoice & Payment Summary",
      summaryVatInclusive: "Total VAT-Inclusive Price",
      nightsCalculated: "Calculated Nights:",
      subtotalBeforeVat: "Base Amount before VAT:",
      vatAmount: "Statutory 15% VAT Component:",
      insuranceAmount: "Required Security Deposit:",
      noInsurance: "0.00 SAR (No deposit charged)",
      grandTotal: "Final Total Amount:",
      vatIncludedFooter: "Includes 15% VAT & all statutory charges",
      directCardsTitle: "Direct Payment via Approved Credit Cards:",
      gatewaySecurity: "Secure, encrypted direct transaction processing powered by Moyasar (licensed by the Saudi Central Bank).",
      payBtn: "Proceed to Pay with Visa / Mastercard",
      incompletePrompt: "* Please complete guest information, select dates and accept statutory terms to proceed.",
      supportQuestion: "Need assistance with booking or payment?",
      whatsapp247: "WhatsApp 24/7",
    },
    receipt: {
      verifyingTitle: "Verifying Payment Transaction...",
      verifyingSubtitle: "Confirming transaction with Moyasar gateway and updating official booking record.",
      successTitle: "Booking Confirmed & Paid Successfully!",
      successSubtitle: "Official digital booking document generated in compliance with Ministry of Tourism regulations.",
      printBtn: "Print Booking Document",
      bookingRef: "Booking Reference ID:",
      guestInfo: "Guest & Reservation Information",
      guestName: "Guest Name:",
      guestPhone: "Mobile Phone:",
      guestEmail: "Email Address:",
      guestCount: "Guests Count:",
      unitInfo: "Accommodation Unit & Dates",
      unitName: "Unit / Service:",
      permitNo: "Facility Permit Number:",
      checkIn: "Check-in Date:",
      checkOut: "Check-out Date:",
      stayDuration: "Stay Duration:",
      feeBreakdown: "Payment & Tax Breakdown",
      baseAmount: "Base Service Rate:",
      vatAmount: "Statutory 15% VAT Component:",
      depositAmount: "Security Deposit:",
      totalPaid: "Total Paid Amount (VAT & Fees Included):",
      payMethod: "Payment Method: Credit Card",
      payStatus: "Payment Status: Confirmed (PAID)",
      termsTitle: "Statutory Terms Applicable to this Booking:",
      term1: "Cancellation & Modification Policy: Requests may be submitted via website or WhatsApp, resolved within max 24 hours.",
      term2: "Refund Policy (Article 23): In case of inability to provide service, guest chooses equivalent alternative or full immediate refund without deductions.",
      term3: "Continuous Support (24/7): Round-the-clock customer support & complaints center.",
      returnHome: "Back to Home",
      viewPolicies: "View All Regulations & Policies",
      failedTitle: "Payment Transaction Incomplete",
      failedDesc: "The payment process was cancelled or card authorization could not be completed.",
      retryBtn: "Retry Payment",
      instantSupport: "Instant WhatsApp Support (24/7)",
    },
    footer: {
      quickLinks: "Quick Navigation",
      statutoryPolicies: "Statutory Policies & Guarantees",
      complaintsSupport: "Inquiries & Complaints (24/7)",
      complaintsDesc: "The establishment is committed to answering all inquiries and complaints round the clock (24/7):",
      bookingPolicy: "Booking & Payment Terms",
      cancelPolicy: "Cancellation & Modification (≤24h SLA)",
      depositPolicy: "Security Deposit Policy",
      refundPolicy: "Refund Policy (Article 23 - Alternative or Instant Refund)",
      adminPortal: "Admin Portal",
      stayFollow: "Follow & Connect",
      stayFollowDesc: "Follow our latest hotel promotions and seasonal offers across our social channels:",
    },
  },
};

export const useAppLang = () => {
  const isEn = computed(() => currentLang.value === "en");
  const isAr = computed(() => currentLang.value === "ar");
  const dir = computed(() => (isEn.value ? "ltr" : "rtl"));
  const t = computed(() => (isEn.value ? translations.en : translations.ar));

  const setLang = (lang: AppLang) => {
    currentLang.value = lang;
    if (typeof window !== "undefined") {
      try {
        localStorage.setItem("app_lang", lang);
        document.documentElement.setAttribute("dir", lang === "en" ? "ltr" : "rtl");
        document.documentElement.setAttribute("lang", lang);
      } catch (e) {
        // ignore
      }
    }
  };

  const toggleLang = () => {
    setLang(currentLang.value === "ar" ? "en" : "ar");
  };

  onMounted(() => {
    if (typeof window !== "undefined") {
      try {
        const saved = localStorage.getItem("app_lang") as AppLang;
        if (saved && (saved === "ar" || saved === "en")) {
          currentLang.value = saved;
        }
        document.documentElement.setAttribute("dir", currentLang.value === "en" ? "ltr" : "rtl");
        document.documentElement.setAttribute("lang", currentLang.value);
      } catch (e) {
        // ignore
      }
    }
  });

  return {
    lang: currentLang,
    isEn,
    isAr,
    dir,
    t,
    setLang,
    toggleLang,
  };
};
